### ISSUE TITLE
Mutations re-generated with no changes

### ISSUE THREAD

**Issue by ericlewis** [mjm/Relay.swift#47]
I have noticed that mutation's seem to be generated each time, even if there are no material changes to the mutation file or mutation. Is this intended behavior?

**Comment by mjm** [comment]
Can you say a little more about the behavior you're seeing? Is the mutation file being generated with meaningless changes? I would expect that it would converge on some particular version of the generated mutation file.

**Comment by mjm** [comment]
I'm having trouble reproducing this. I was testing against the RelayTodo example project in this repo, and I do see the one mutation there having a very recent modified time, but I didn't check it before running the compiler (my bad), and subsequent runs of the compiler are not changing the timestamp. I also tested another project that has a mutation, and I'm not seeing the timestamp change, so I haven't found any evidence that the file is getting rewritten.

Can you provide a little more information about how you're observing this effect and what problems it's causing? Things like specific sequences of commands and their output would really help here :)
